# Generated by Django 2.1.1 on 2020-02-08 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='modulePlantLink',
            fields=[
                ('plant_type', models.CharField(max_length=45)),
                ('mcu_no', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'modulePlantLink',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='dataMCU',
            fields=[
                ('mcu_no', models.ForeignKey(db_column='mcu_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webapp.modulePlantLink')),
                ('data_date', models.DateField()),
                ('soil_moisture', models.IntegerField()),
                ('temp', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('light_reading', models.IntegerField()),
                ('heat_index', models.IntegerField()),
                ('battery_lvl', models.IntegerField()),
            ],
            options={
                'db_table': 'dataMCU',
                'managed': False,
            },
        ),
    ]
